// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAffrerNXt4XCNHQtqG0LRksS639FETNJQ',
    appId: '1:236163366874:web:5ce869a27271ac30978ae3',
    messagingSenderId: '236163366874',
    projectId: 'canteen-dummy-daiict',
    authDomain: 'canteen-dummy-daiict.firebaseapp.com',
    storageBucket: 'canteen-dummy-daiict.appspot.com',
    measurementId: 'G-WFFLYB0HDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0xFpnFHvHM7zdwEozd2E2tkZrbqZt-0M',
    appId: '1:236163366874:android:ef5a2d2e75a655a7978ae3',
    messagingSenderId: '236163366874',
    projectId: 'canteen-dummy-daiict',
    storageBucket: 'canteen-dummy-daiict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9d2nkFGp9xJXFe53Mq8jjdCQd_vsQoxI',
    appId: '1:236163366874:ios:98937b2eb7bbf086978ae3',
    messagingSenderId: '236163366874',
    projectId: 'canteen-dummy-daiict',
    storageBucket: 'canteen-dummy-daiict.appspot.com',
    iosClientId: '236163366874-9gkpl44kkhg531qbros287vl0dgijnli.apps.googleusercontent.com',
    iosBundleId: 'com.example.canteenDaiict',
  );
}
